import tseslint from "typescript-eslint";

// A-102's per-member lint. index.ts is generated by `supabase gen types` and
// never hand-edited (A-98), so what is linted here is the generator's output.
export default tseslint.config(...tseslint.configs.recommended, {
  rules: {
    "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    // The generator emits `any` for an untyped Postgres shape; its output, not our choice.
    "@typescript-eslint/no-explicit-any": "off",
  },
});
